[build]
  publish = "public"
  command = ""

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/shop/products/*"
  to = "https://divalgoni.myshopify.com/products/:splat"
  status = 200
  force = true
